# site title
title: output

# user name or organization name
user: charlzyx

# issue repository
repository: o

# multi-author
authors: charlzyx

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: 3#9ca2b7ff311754a37f4c9b5eed33b1abb5dd3d4

# posts per page
perpage: 10


# advance config

# organization repository (?)
organization: false

# post order
# order by create time" or "update time"
# 'UPDATED_AT' or 'CREATED_AT'
order: 'UPDATED_AT'
